// <auto-generated />
namespace FATEA.PetNet.DataAccess.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnimalTableCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnimalTableCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201608201302144_AnimalTableCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
